// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

package com.company.mobilecppmemorytest;

public abstract class FatherCallback {
    public abstract void onResult(String result);
}
