// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logger.djinni

package com.company.mobilecppmemorytest;

public abstract class Logger {
    public abstract void log(String stringLog);
}
