// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

package com.company.mobilecppmemorytest;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ModelFather {
    public abstract void simulateWork(FatherCallback fatherCallback);

    public static native ModelFather create(NetworkRequest networkRequest, Logger logger);

    private static final class CppProxy extends ModelFather
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void simulateWork(FatherCallback fatherCallback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_simulateWork(this.nativeRef, fatherCallback);
        }
        private native void native_simulateWork(long _nativeRef, FatherCallback fatherCallback);
    }
}
