// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.company.mobilecppmemorytest;

public final class NetworkRequestResponse {


    /*package*/ final boolean mSucceed;

    /*package*/ final String mData;

    /*package*/ final int mHttpStatusCode;

    public NetworkRequestResponse(
            boolean succeed,
            String data,
            int httpStatusCode) {
        this.mSucceed = succeed;
        this.mData = data;
        this.mHttpStatusCode = httpStatusCode;
    }

    public boolean getSucceed() {
        return mSucceed;
    }

    public String getData() {
        return mData;
    }

    public int getHttpStatusCode() {
        return mHttpStatusCode;
    }

    @Override
    public String toString() {
        return "NetworkRequestResponse{" +
                "mSucceed=" + mSucceed +
                "," + "mData=" + mData +
                "," + "mHttpStatusCode=" + mHttpStatusCode +
        "}";
    }

}
