// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.company.mobilecppmemorytest;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class NetworkRequestCallback {
    public abstract void onResponse(NetworkRequestResponse networkRequestResponse);

    private static final class CppProxy extends NetworkRequestCallback
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void onResponse(NetworkRequestResponse networkRequestResponse)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onResponse(this.nativeRef, networkRequestResponse);
        }
        private native void native_onResponse(long _nativeRef, NetworkRequestResponse networkRequestResponse);
    }
}
