// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.company.mobilecppmemorytest;

public abstract class NetworkRequest {
    public abstract void httpGetRequest(String stringUrl, NetworkRequestCallback callback);
}
