// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

package com.company.mobilecppmemorytest;

public abstract class SonCallback {
    public abstract void onResult(String result);
}
