// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#include "NativeSonCallback.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSonCallback::NativeSonCallback() : ::djinni::JniInterface<::mobilecppmemorytest::SonCallback, NativeSonCallback>() {}

NativeSonCallback::~NativeSonCallback() = default;

NativeSonCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeSonCallback::JavaProxy::~JavaProxy() = default;

void NativeSonCallback::JavaProxy::onResult(const std::string & c_result) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSonCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onResult,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_result)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
