// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "NetworkRequestCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeNetworkRequestCallback final : ::djinni::JniInterface<::mobilecppmemorytest::NetworkRequestCallback, NativeNetworkRequestCallback> {
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::NetworkRequestCallback>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::NetworkRequestCallback>;
    using JniType = jobject;

    using Boxed = NativeNetworkRequestCallback;

    ~NativeNetworkRequestCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeNetworkRequestCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeNetworkRequestCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeNetworkRequestCallback();
    friend ::djinni::JniClass<NativeNetworkRequestCallback>;
    friend ::djinni::JniInterface<::mobilecppmemorytest::NetworkRequestCallback, NativeNetworkRequestCallback>;

};

}  // namespace djinni_generated
