// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#include "NativeNetworkRequest.hpp"  // my header
#include "Marshal.hpp"
#include "NativeNetworkRequestCallback.hpp"

namespace djinni_generated {

NativeNetworkRequest::NativeNetworkRequest() : ::djinni::JniInterface<::mobilecppmemorytest::NetworkRequest, NativeNetworkRequest>() {}

NativeNetworkRequest::~NativeNetworkRequest() = default;

NativeNetworkRequest::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeNetworkRequest::JavaProxy::~JavaProxy() = default;

void NativeNetworkRequest::JavaProxy::httpGetRequest(const std::string & c_stringUrl, const std::shared_ptr<::mobilecppmemorytest::NetworkRequestCallback> & c_callback) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeNetworkRequest>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_httpGetRequest,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_stringUrl)),
                           ::djinni::get(::djinni_generated::NativeNetworkRequestCallback::fromCpp(jniEnv, c_callback)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
