// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#include "NativeModelFather.hpp"  // my header
#include "NativeFatherCallback.hpp"
#include "NativeLogger.hpp"
#include "NativeNetworkRequest.hpp"

namespace djinni_generated {

NativeModelFather::NativeModelFather() : ::djinni::JniInterface<::mobilecppmemorytest::ModelFather, NativeModelFather>("com/company/mobilecppmemorytest/ModelFather$CppProxy") {}

NativeModelFather::~NativeModelFather() = default;


CJNIEXPORT void JNICALL Java_com_company_mobilecppmemorytest_ModelFather_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::mobilecppmemorytest::ModelFather>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_company_mobilecppmemorytest_ModelFather_create(JNIEnv* jniEnv, jobject /*this*/, jobject j_networkRequest, jobject j_logger)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::mobilecppmemorytest::ModelFather::create(::djinni_generated::NativeNetworkRequest::toCpp(jniEnv, j_networkRequest),
                                                            ::djinni_generated::NativeLogger::toCpp(jniEnv, j_logger));
        return ::djinni::release(::djinni_generated::NativeModelFather::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_company_mobilecppmemorytest_ModelFather_00024CppProxy_native_1simulateWork(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_fatherCallback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::mobilecppmemorytest::ModelFather>(nativeRef);
        ref->simulateWork(::djinni_generated::NativeFatherCallback::toCpp(jniEnv, j_fatherCallback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
