// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logger.djinni

#pragma once

#include "Logger.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeLogger final : ::djinni::JniInterface<::mobilecppmemorytest::Logger, NativeLogger> {
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::Logger>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::Logger>;
    using JniType = jobject;

    using Boxed = NativeLogger;

    ~NativeLogger();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLogger>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLogger>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLogger();
    friend ::djinni::JniClass<NativeLogger>;
    friend ::djinni::JniInterface<::mobilecppmemorytest::Logger, NativeLogger>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::mobilecppmemorytest::Logger
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void log(const std::string & stringLog) override;

    private:
        friend ::djinni::JniInterface<::mobilecppmemorytest::Logger, ::djinni_generated::NativeLogger>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/company/mobilecppmemorytest/Logger") };
    const jmethodID method_log { ::djinni::jniGetMethodID(clazz.get(), "log", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
