// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#include "NativeNetworkRequestResponse.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeNetworkRequestResponse::NativeNetworkRequestResponse() = default;

NativeNetworkRequestResponse::~NativeNetworkRequestResponse() = default;

auto NativeNetworkRequestResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeNetworkRequestResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.succeed)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.data)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.httpStatusCode)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeNetworkRequestResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeNetworkRequestResponse>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSucceed)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mData)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mHttpStatusCode))};
}

}  // namespace djinni_generated
