// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#include "NativeModelSon.hpp"  // my header
#include "NativeLogger.hpp"
#include "NativeNetworkRequest.hpp"
#include "NativeSonCallback.hpp"

namespace djinni_generated {

NativeModelSon::NativeModelSon() : ::djinni::JniInterface<::mobilecppmemorytest::ModelSon, NativeModelSon>("com/company/mobilecppmemorytest/ModelSon$CppProxy") {}

NativeModelSon::~NativeModelSon() = default;


CJNIEXPORT void JNICALL Java_com_company_mobilecppmemorytest_ModelSon_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::mobilecppmemorytest::ModelSon>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_company_mobilecppmemorytest_ModelSon_create(JNIEnv* jniEnv, jobject /*this*/, jobject j_networkRequest, jobject j_logger)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::mobilecppmemorytest::ModelSon::create(::djinni_generated::NativeNetworkRequest::toCpp(jniEnv, j_networkRequest),
                                                         ::djinni_generated::NativeLogger::toCpp(jniEnv, j_logger));
        return ::djinni::release(::djinni_generated::NativeModelSon::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_company_mobilecppmemorytest_ModelSon_00024CppProxy_native_1simulateWork(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_sonCallback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::mobilecppmemorytest::ModelSon>(nativeRef);
        ref->simulateWork(::djinni_generated::NativeSonCallback::toCpp(jniEnv, j_sonCallback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
