// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#pragma once

#include "FatherCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeFatherCallback final : ::djinni::JniInterface<::mobilecppmemorytest::FatherCallback, NativeFatherCallback> {
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::FatherCallback>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::FatherCallback>;
    using JniType = jobject;

    using Boxed = NativeFatherCallback;

    ~NativeFatherCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeFatherCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeFatherCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeFatherCallback();
    friend ::djinni::JniClass<NativeFatherCallback>;
    friend ::djinni::JniInterface<::mobilecppmemorytest::FatherCallback, NativeFatherCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::mobilecppmemorytest::FatherCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onResult(const std::string & result) override;

    private:
        friend ::djinni::JniInterface<::mobilecppmemorytest::FatherCallback, ::djinni_generated::NativeFatherCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/company/mobilecppmemorytest/FatherCallback") };
    const jmethodID method_onResult { ::djinni::jniGetMethodID(clazz.get(), "onResult", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
