// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#pragma once

#include "ModelSon.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeModelSon final : ::djinni::JniInterface<::mobilecppmemorytest::ModelSon, NativeModelSon> {
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::ModelSon>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::ModelSon>;
    using JniType = jobject;

    using Boxed = NativeModelSon;

    ~NativeModelSon();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeModelSon>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeModelSon>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeModelSon();
    friend ::djinni::JniClass<NativeModelSon>;
    friend ::djinni::JniInterface<::mobilecppmemorytest::ModelSon, NativeModelSon>;

};

}  // namespace djinni_generated
