// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "MCMTNetworkRequestResponse.h"
#import <Foundation/Foundation.h>


@interface MCMTNetworkRequestCallback : NSObject

- (void)onResponse:(nonnull MCMTNetworkRequestResponse *)networkRequestResponse;

@end
