// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#include "SonCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MCMTSonCallback;

namespace djinni_generated {

class SonCallback
{
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::SonCallback>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::SonCallback>;
    using ObjcType = id<MCMTSonCallback>;

    using Boxed = SonCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

