// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import <Foundation/Foundation.h>

@interface MCMTNetworkRequestResponse : NSObject
- (nonnull instancetype)initWithSucceed:(BOOL)succeed
                                   data:(nonnull NSString *)data
                         httpStatusCode:(int32_t)httpStatusCode;
+ (nonnull instancetype)NetworkRequestResponseWithSucceed:(BOOL)succeed
                                                     data:(nonnull NSString *)data
                                           httpStatusCode:(int32_t)httpStatusCode;

@property (nonatomic, readonly) BOOL succeed;

@property (nonatomic, readonly, nonnull) NSString * data;

@property (nonatomic, readonly) int32_t httpStatusCode;

@end
