// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#import <Foundation/Foundation.h>


@protocol MCMTFatherCallback

- (void)onResult:(nonnull NSString *)result;

@end
