// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#include "FatherCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MCMTFatherCallback;

namespace djinni_generated {

class FatherCallback
{
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::FatherCallback>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::FatherCallback>;
    using ObjcType = id<MCMTFatherCallback>;

    using Boxed = FatherCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

