// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#import <Foundation/Foundation.h>
@class MCMTModelSon;
@protocol MCMTLogger;
@protocol MCMTNetworkRequest;
@protocol MCMTSonCallback;


@interface MCMTModelSon : NSObject

+ (nullable MCMTModelSon *)create:(nullable id<MCMTNetworkRequest>)networkRequest
                           logger:(nullable id<MCMTLogger>)logger;

- (void)simulateWork:(nullable id<MCMTSonCallback>)sonCallback;

@end
