// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import <Foundation/Foundation.h>
@class MCMTNetworkRequestCallback;


@protocol MCMTNetworkRequest

- (void)httpGetRequest:(nonnull NSString *)stringUrl
              callback:(nullable MCMTNetworkRequestCallback *)callback;

@end
