// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#import <Foundation/Foundation.h>


@protocol MCMTSonCallback

- (void)onResult:(nonnull NSString *)result;

@end
