// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#import "MCMTModelSon+Private.h"
#import "MCMTModelSon.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "MCMTLogger+Private.h"
#import "MCMTNetworkRequest+Private.h"
#import "MCMTSonCallback+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface MCMTModelSon ()

- (id)initWithCpp:(const std::shared_ptr<::mobilecppmemorytest::ModelSon>&)cppRef;

@end

@implementation MCMTModelSon {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::mobilecppmemorytest::ModelSon>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::mobilecppmemorytest::ModelSon>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable MCMTModelSon *)create:(nullable id<MCMTNetworkRequest>)networkRequest
                           logger:(nullable id<MCMTLogger>)logger {
    try {
        auto objcpp_result_ = ::mobilecppmemorytest::ModelSon::create(::djinni_generated::NetworkRequest::toCpp(networkRequest),
                                                                      ::djinni_generated::Logger::toCpp(logger));
        return ::djinni_generated::ModelSon::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)simulateWork:(nullable id<MCMTSonCallback>)sonCallback {
    try {
        _cppRefHandle.get()->simulateWork(::djinni_generated::SonCallback::toCpp(sonCallback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ModelSon::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ModelSon::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<MCMTModelSon>(cpp);
}

}  // namespace djinni_generated

@end
