// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "MCMTNetworkRequest+Private.h"
#import "MCMTNetworkRequest.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "MCMTNetworkRequestCallback+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class NetworkRequest::ObjcProxy final
: public ::mobilecppmemorytest::NetworkRequest
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void httpGetRequest(const std::string & c_stringUrl, const std::shared_ptr<::mobilecppmemorytest::NetworkRequestCallback> & c_callback) override
    {
        @autoreleasepool {
            [Handle::get() httpGetRequest:(::djinni::String::fromCpp(c_stringUrl))
                                 callback:(::djinni_generated::NetworkRequestCallback::fromCpp(c_callback))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto NetworkRequest::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto NetworkRequest::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
