// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "MCMTNetworkRequestResponse.h"


@implementation MCMTNetworkRequestResponse

- (nonnull instancetype)initWithSucceed:(BOOL)succeed
                                   data:(nonnull NSString *)data
                         httpStatusCode:(int32_t)httpStatusCode
{
    if (self = [super init]) {
        _succeed = succeed;
        _data = [data copy];
        _httpStatusCode = httpStatusCode;
    }
    return self;
}

+ (nonnull instancetype)NetworkRequestResponseWithSucceed:(BOOL)succeed
                                                     data:(nonnull NSString *)data
                                           httpStatusCode:(int32_t)httpStatusCode
{
    return [[self alloc] initWithSucceed:succeed
                                    data:data
                          httpStatusCode:httpStatusCode];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p succeed:%@ data:%@ httpStatusCode:%@>", self.class, (void *)self, @(self.succeed), self.data, @(self.httpStatusCode)];
}

@end
