// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#include "NetworkRequestCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCMTNetworkRequestCallback;

namespace djinni_generated {

class NetworkRequestCallback
{
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::NetworkRequestCallback>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::NetworkRequestCallback>;
    using ObjcType = MCMTNetworkRequestCallback*;

    using Boxed = NetworkRequestCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

