// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#include "ModelFather.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCMTModelFather;

namespace djinni_generated {

class ModelFather
{
public:
    using CppType = std::shared_ptr<::mobilecppmemorytest::ModelFather>;
    using CppOptType = std::shared_ptr<::mobilecppmemorytest::ModelFather>;
    using ObjcType = MCMTModelFather*;

    using Boxed = ModelFather;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

