// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#import <Foundation/Foundation.h>
@class MCMTModelFather;
@protocol MCMTFatherCallback;
@protocol MCMTLogger;
@protocol MCMTNetworkRequest;


@interface MCMTModelFather : NSObject

+ (nullable MCMTModelFather *)create:(nullable id<MCMTNetworkRequest>)networkRequest
                              logger:(nullable id<MCMTLogger>)logger;

- (void)simulateWork:(nullable id<MCMTFatherCallback>)fatherCallback;

@end
