// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "MCMTNetworkRequestResponse.h"
#include "NetworkRequestResponse.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCMTNetworkRequestResponse;

namespace djinni_generated {

struct NetworkRequestResponse
{
    using CppType = ::mobilecppmemorytest::NetworkRequestResponse;
    using ObjcType = MCMTNetworkRequestResponse*;

    using Boxed = NetworkRequestResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
