// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#pragma once

#include <string>

namespace mobilecppmemorytest {

class FatherCallback {
public:
    virtual ~FatherCallback() {}

    virtual void onResult(const std::string & result) = 0;
};

}  // namespace mobilecppmemorytest
