// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logger.djinni

#pragma once

#include <string>

namespace mobilecppmemorytest {

class Logger {
public:
    virtual ~Logger() {}

    virtual void log(const std::string & stringLog) = 0;
};

}  // namespace mobilecppmemorytest
