// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from father.djinni

#pragma once

#include <memory>

namespace mobilecppmemorytest {

class FatherCallback;
class Logger;
class NetworkRequest;

class ModelFather {
public:
    virtual ~ModelFather() {}

    static std::shared_ptr<ModelFather> create(const std::shared_ptr<NetworkRequest> & networkRequest, const std::shared_ptr<Logger> & logger);

    virtual void simulateWork(const std::shared_ptr<FatherCallback> & fatherCallback) = 0;
};

}  // namespace mobilecppmemorytest
