// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace mobilecppmemorytest {

struct NetworkRequestResponse final {
    bool succeed;
    std::string data;
    int32_t httpStatusCode;

    NetworkRequestResponse(bool succeed_,
                           std::string data_,
                           int32_t httpStatusCode_)
    : succeed(std::move(succeed_))
    , data(std::move(data_))
    , httpStatusCode(std::move(httpStatusCode_))
    {}
};

}  // namespace mobilecppmemorytest
