// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from son.djinni

#pragma once

#include <string>

namespace mobilecppmemorytest {

class SonCallback {
public:
    virtual ~SonCallback() {}

    virtual void onResult(const std::string & result) = 0;
};

}  // namespace mobilecppmemorytest
